version: '3.1'
services:
  app:
    environment:
      - MONGODB_URL=amos_mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=pass
      - HOST_URL=0.0.0.0
      - HOST_PORT=8000
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python -u app.py
    links:
      - db
  db:
    image: mongo:latest
    hostname: amos_mongodb
    environment:
      - MONGO_INITDB_DATABASE=dpms_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
       - ./tmpDatabase:/docker-databases
    ports:
      - 27017:27017
