version: '3.1'
services:
  app-amos:
    container_name: flask-app
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: ["python", "app.py"]
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    # environment:
      # - MONGO_INITDB_DATABASE=animal_db
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=pass
    # volumes:
      # - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
    command: mongod --bind_ip_all